kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-csas-argocd-sys-argocd-application-controller-admin
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: csas-argocd-sys
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
